# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77c8bf7442a5d9558f205b8f6e37be964210a14f3940f8c8e85b71be890db152b51d11239d3351c7d1d60fa1980fd761ab98a09cd8e1580a13cc61603b477ec0

test:
  secret_key_base: 055f5530a109add525382601d3cdfcd3bca30cbb709cdc9831c95038fdc2e68cdaa563c8d6b8a3195c96a4898a82122aeae531b46016bc66ddbeaae3255275cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
